name: Spyrothon API

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: prod

    steps:
      - uses: actions/checkout@v3

      - name: Install Erlang/Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 24.0.4
          elixir-version: 1.12.2

      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Install Dependencies
        run: mix deps.get

      - name: Compile application
        run: mix compile

      - name: Build Mix Release
        run: |
          mix release graphics_api
