name: Spyrothon API

on:
  push:
    branches: [main]

env:
  MIX_ENV: prod
  API_DATABASE_URL: ${{ secrets.API_DATABASE_URL }}
  TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
  TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      NODE_ENV: ci

    steps:
      - uses: actions/checkout@v2

      - name: Install Erlang/Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 24.0.4
          elixir-version: 1.12.2

      - name: Install Dependencies
        run: |
          mix deps.get
          mix compile

      - name: Build Mix Release
        run: |
          mix release graphics_api
